version: '3.4'

services:
  cetaitquoilecontexte.web.services.ui:
    image: cetaitquoilecontextewebservicesui
    build:
      context: .
      dockerfile: CetaitQuoiLeContexte.Web.Services.UI/Dockerfile

  cetaitquoilecontexte.web.ui:
    image: cetaitquoilecontextewebui
    build:
      context: .
      dockerfile: ../CetaitQuoiLeContexte.Web.UI/Dockerfile


  cetaitquoilecontexte.razor.web.ui:
    image: cetaitquoilecontexterazorwebui
    build:
      context: .
      dockerfile: ../CetaitQuoiLeContexte.Razor.Web.UI/Dockerfile

