version: '3.4'

services:
  cetaitquoilecontexte.web.services.ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  cetaitquoilecontexte.web.ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  cetaitquoilecontexte.razor.web.ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

